"""HTML report generator."""
from __future__ import annotations
from datetime import datetime
from typing import Any

from .base import ReportGenerator
from .models import ReportData


class HTMLReportGenerator(ReportGenerator):
    """Generate HTML report."""
    
    def generate(self) -> str:
        """Generate HTML report content."""
        return self._generate_html()
    
    def _generate_html(self) -> str:
        html = f"""<!DOCTYPE html>
<html lang="{self.data.language}">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{self.data.project_name} - Analysis Report</title>
    <style>
        body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; margin: 40px; color: #333; }}
        h1 {{ color: #2563EB; border-bottom: 2px solid #2563EB; padding-bottom: 10px; }}
        h2 {{ color: #444; margin-top: 30px; }}
        table {{ border-collapse: collapse; width: 100%; margin: 20px 0; }}
        th, td {{ border: 1px solid #ddd; padding: 8px; text-align: left; }}
        th {{ background-color: #2563EB; color: white; }}
        tr:nth-child(even) {{ background-color: #f9f9f9; }}
        .info-box {{ background: #f0f7ff; padding: 15px; border-radius: 5px; margin: 10px 0; }}
        .badge {{ display: inline-block; padding: 3px 8px; border-radius: 3px; font-size: 12px; }}
        .badge-success {{ background: #d1fae5; color: #065f46; }}
        .badge-warning {{ background: #fef3c7; color: #92400e; }}
        .badge-danger {{ background: #fee2e2; color: #991b1b; }}
        .footer {{ margin-top: 40px; padding-top: 20px; border-top: 1px solid #ddd; color: #666; font-size: 12px; }}
    </style>
</head>
<body>
    <h1>{self._truncate(self.data.project_name)}</h1>
    
    <div class="info-box">
        <strong>報告產生時間:</strong> {self.data.created_at.strftime('%Y-%m-%d %H:%M:%S')}<br>
        <strong>操作者:</strong> {self.data.operator}<br>
        <strong>專案名称:</strong> {self.data.project_name}
    </div>
    
    <h2>資料來源</h2>
    <table>
        <tr><th>項目</th><th>值</th></tr>
        <tr><td>資料集 ID</td><td>{self.data.dataset_id or 'N/A'}</td></tr>
        <tr><td>來源檔案</td><td>{self.data.source_file or 'N/A'}</td></tr>
        <tr><td>資料列數</td><td>{self.data.row_count}</td></tr>
        <tr><td>欄位數</td><td>{self.data.column_count}</td></tr>
    </table>
    
    <h2>欄位角色</h2>
    <table>
        <tr><th>欄位名称</th><th>角色</th><th>信心度</th></tr>
"""
        for field in self.data.fields:
            role = field.get('role', 'unknown')
            confidence = self._format_percentage(field.get('confidence', 0))
            badge_class = 'badge-success' if role == 'output' else 'badge-warning'
            html += f"""
        <tr>
            <td>{field.get('name', 'N/A')}</td>
            <td><span class="badge {badge_class}">{role}</span></td>
            <td>{confidence}</td>
        </tr>
"""
        
        html += f"""
    </table>
    
    <div class="footer">
        <p>Generated by Process Intelligence Platform v{self.data.version} | {(datetime.now()).strftime('%Y-%m-%d %H:%M:%S')}</p>
    </div>
</body>
</html>
"""
        return html
