export type AppTab =
  | 'project'
  | 'dataImport'
  | 'processDefine'
  | 'exploration'
  | 'modelCenter'
  | 'validation'
  | 'monteCarlo'
  | 'copula'
  | 'prediction'
  | 'reports'
  | 'spc'
  | 'processFlow'
  | 'dataAssets'
  | 'settings'
