export type AppTab =
  | 'project'
  | 'dataImport'
  | 'dataCheck'
  | 'processDefine'
  | 'exploration'
  | 'modelCenter'
  | 'validation'
  | 'monteCarlo'
  | 'prediction'
  | 'reports'
  | 'settings'
