export type GuideSection = { title: string; purpose: string; principle: string; formula: string; interpretation: string; limits: string; recommendation: string }
const common = {
  'zh-TW': { purpose: '說明目前頁面的用途與結果。', principle: '以所選資料與統計假設為判讀基礎。', formula: '請參考頁面指標與圖表註記。', interpretation: '綜合數值、圖表與工程知識判讀。', limits: '結果描述所選樣本，不代表母體或因果結論。', recommendation: '決策前確認資料品質與分析假設。' },
  en: { purpose: 'Explain the purpose and results of this page.', principle: 'Interpret results using the selected data and statistical assumptions.', formula: 'Refer to the metrics and chart annotations on the page.', interpretation: 'Combine numerical results, charts, and engineering knowledge.', limits: 'Results describe the selected sample and do not prove population or causality.', recommendation: 'Verify data quality and assumptions before decisions.' },
  'es-MX': { purpose: 'Explica el propósito y los resultados de esta página.', principle: 'Interpreta con los datos seleccionados y los supuestos estadísticos.', formula: 'Consulta las métricas y anotaciones del gráfico.', interpretation: 'Combina resultados numéricos, gráficos y conocimiento de ingeniería.', limits: 'Los resultados describen la muestra y no prueban población ni causalidad.', recommendation: 'Verifica calidad de datos y supuestos antes de decidir.' },
} as const
const topics: Record<string, Partial<Record<keyof typeof common, Partial<GuideSection>>>> = {
  distribution: { 'zh-TW': { purpose: '比較所選欄位的候選分布。', principle: 'AIC／BIC 比較相對配適；KS 檢定檢查一致性。', formula: 'AIC=2k−2ln(L)；BIC=kln(n)−2ln(L)。', interpretation: 'AIC／BIC 越低通常越佳；KS p-value 越大表示本樣本未拒絕。', limits: '樣本配適不代表母體一定服從該分布。', recommendation: '確認參數、圖形與工程合理性後再用於模擬。' }, en: { purpose: 'Compare candidate distributions for the selected column.', principle: 'AIC/BIC compare relative fit; KS checks consistency.', formula: 'AIC=2k−2ln(L); BIC=kln(n)−2ln(L).', interpretation: 'Lower AIC/BIC is usually preferable; a larger KS p-value means the sample does not reject the distribution.', limits: 'A sample fit does not prove the population distribution.', recommendation: 'Check parameters, plots, and engineering plausibility before simulation.' }, 'es-MX': { purpose: 'Compara distribuciones candidatas para la columna seleccionada.', principle: 'AIC/BIC comparan el ajuste; KS verifica consistencia.', formula: 'AIC=2k−2ln(L); BIC=kln(n)−2ln(L).', interpretation: 'Un AIC/BIC menor suele ser preferible; un p-value KS mayor indica que la muestra no rechaza la distribución.', limits: 'El ajuste de una muestra no prueba la distribución poblacional.', recommendation: 'Revisa parámetros, gráficos y plausibilidad antes de simular.' } },
  trend: { 'zh-TW': { purpose: '觀察欄位隨序列的方向、漂移與控制界線狀態。', principle: '以序列差異與連續同向點辨識可能漂移。', formula: '變化量 = 末值 − 首值；控制界線外點需調查。', interpretation: '注意長連續上升／下降、突變與界線外點。', recommendation: '檢查時間排序、單位、校正，並依批次或機台分層。' }, en: { purpose: 'Inspect direction, drift, and control-limit status over sequence order.', principle: 'Sequence differences and same-direction runs indicate possible drift.', formula: 'Change = last value − first value; investigate points beyond limits.', interpretation: 'Watch sustained runs, abrupt shifts, and out-of-limit points.', recommendation: 'Check time order, units, calibration, and segment by batch or machine.' }, 'es-MX': { purpose: 'Observa dirección, deriva y límites de control por orden de secuencia.', principle: 'Las diferencias y rachas en una dirección pueden indicar deriva.', formula: 'Cambio = último − primero; investiga puntos fuera de límites.', interpretation: 'Revisa rachas sostenidas, cambios bruscos y puntos fuera de límite.', recommendation: 'Verifica orden temporal, unidades, calibración y segmenta por lote o máquina.' } },
  timeseries: { 'zh-TW': { purpose: '計算延遲、差分、移動統計與時間序列特徵。', principle: '時間順序與自相關會影響特徵與模型假設。', formula: 'lag_k = x_t−k；差分 = x_t−x_t−1。', interpretation: '檢查缺值、重複時間、間隔不一致與自相關。', recommendation: '先校正時間戳並確認平穩性，再建立預測模型。' }, en: { purpose: 'Compute lags, differences, rolling statistics, and time-series features.', principle: 'Time order and autocorrelation affect features and model assumptions.', formula: 'lag_k = x_t−k; difference = x_t−x_t−1.', interpretation: 'Check missing or duplicate times, irregular intervals, and autocorrelation.', recommendation: 'Correct timestamps and assess stationarity before forecasting.' }, 'es-MX': { purpose: 'Calcula retardos, diferencias, estadísticas móviles y características temporales.', principle: 'El orden temporal y la autocorrelación afectan supuestos y características.', formula: 'lag_k = x_t−k; diferencia = x_t−x_t−1.', interpretation: 'Revisa tiempos faltantes o duplicados, intervalos irregulares y autocorrelación.', recommendation: 'Corrige marcas de tiempo y evalúa estacionariedad antes de pronosticar.' } },
  grr: { 'zh-TW': { purpose: '評估量測系統的重複性與再現性。', principle: '將量具與操作者變異和零件間變異分離。', formula: '%GRR = GRR變異／總變異 × 100%。', interpretation: '低%GRR較佳；邊界結果須依應用重要性判斷。', recommendation: '優先改善量具固定、校正與操作一致性後重新量測。' }, en: { purpose: 'Evaluate repeatability and reproducibility of the measurement system.', principle: 'Separate equipment and operator variation from part-to-part variation.', formula: '%GRR = GRR variation / total variation × 100%.', interpretation: 'Lower %GRR is better; judge marginal results by application criticality.', recommendation: 'Improve fixture stability, calibration, and operator consistency, then remeasure.' }, 'es-MX': { purpose: 'Evalúa repetibilidad y reproducibilidad del sistema de medición.', principle: 'Separa variación del equipo y operador de la variación pieza a pieza.', formula: '%GRR = variación GRR / variación total × 100%.', interpretation: 'Un %GRR menor es mejor; juzga resultados marginales según criticidad.', recommendation: 'Mejora fijación, calibración y consistencia del operador y vuelve a medir.' } },
  spc: { 'zh-TW': { purpose: '用控制圖監控製程穩定性與特殊原因變異。', formula: '控制界線通常為中心線 ± 3σ。', recommendation: '先確認時間順序與量測系統，再調查界線外點。' }, en: { purpose: 'Monitor process stability and special-cause variation with control charts.', formula: 'Control limits are commonly center line ± 3σ.', recommendation: 'Verify time order and measurement system before investigating out-of-limit points.' }, 'es-MX': { purpose: 'Monitorea estabilidad y causas especiales con gráficos de control.', formula: 'Los límites suelen ser línea central ± 3σ.', recommendation: 'Verifica orden temporal y sistema de medición antes de investigar puntos fuera de límite.' } },
  modelCenter: { 'zh-TW': { purpose: '比較模型配適、效應與診斷結果。', formula: '依模型類型使用迴歸、ANOVA、SHAP 或敏感度指標。', recommendation: '比較驗證指標與殘差後，再選模型進行實驗。' }, en: { purpose: 'Compare model fit, effects, and diagnostics.', formula: 'Use regression, ANOVA, SHAP, or sensitivity metrics by model type.', recommendation: 'Review validation metrics and residuals before selecting a model for experiments.' }, 'es-MX': { purpose: 'Compara ajuste, efectos y diagnósticos de modelos.', formula: 'Usa regresión, ANOVA, SHAP o sensibilidad según el modelo.', recommendation: 'Revisa métricas de validación y residuos antes de elegir un modelo.' } },
  monteCarlo: { 'zh-TW': { purpose: '依輸入分布抽樣，估計輸出落在規格外的風險。', formula: 'NG 機率 = 超出規格的模擬次數／總模擬次數。', recommendation: '確認抽樣分布、相關性、種子與規格設定，再解讀 NG 機率。' }, en: { purpose: 'Sample input distributions to estimate output specification risk.', formula: 'NG probability = simulations outside specification / total simulations.', recommendation: 'Check distributions, correlations, seed, and specifications before interpreting risk.' }, 'es-MX': { purpose: 'Muestrea distribuciones de entrada para estimar riesgo fuera de especificación.', formula: 'Probabilidad NG = simulaciones fuera de especificación / total.', recommendation: 'Revisa distribuciones, correlaciones, semilla y especificaciones antes de interpretar.' } },
  validation: { 'zh-TW': { purpose: '比較候選模型並規劃可驗證的後續實驗。', recommendation: '確認模型輸入範圍涵蓋實際製程，再執行建議實驗。' }, en: { purpose: 'Compare candidate models and plan verifiable follow-up experiments.', recommendation: 'Ensure model inputs cover the real process before running suggested experiments.' }, 'es-MX': { purpose: 'Compara modelos candidatos y planifica experimentos verificables.', recommendation: 'Asegura que las entradas cubran el proceso real antes de ejecutar experimentos.' } },
  reports: { 'zh-TW': { purpose: '產生可追溯的分析報告與版本紀錄。', recommendation: '檢查報告 metadata、資料集版本與模型版本後再分享。' }, en: { purpose: 'Generate traceable analysis reports and version records.', recommendation: 'Check report metadata, dataset version, and model version before sharing.' }, 'es-MX': { purpose: 'Genera informes de análisis y registros de versión trazables.', recommendation: 'Revisa metadatos, versión de datos y modelo antes de compartir.' } },
}
export function getGuideSection(tab: string, subtab: string | undefined, language: string): GuideSection {
  const lang = (language in common ? language : 'en') as keyof typeof common
  const base = { ...common[lang], title: '' }
  const topic = topics[subtab && tab === 'exploration' ? subtab : tab]?.[lang]
  return { ...base, ...topic, title: '' }
}
