export type GuideSection = { title: string; purpose: string; principle: string; formula: string; interpretation: string; limits: string; recommendation: string }
const common = {
  'zh-TW': { purpose: '說明目前頁面的用途與結果。', principle: '以所選資料與統計假設為判讀基礎。', formula: '請參考頁面指標與圖表註記。', interpretation: '綜合數值、圖表與工程知識判讀。', limits: '結果描述所選樣本，不代表母體或因果結論。', recommendation: '決策前確認資料品質與分析假設。' },
  en: { purpose: 'Explain the purpose and results of this page.', principle: 'Interpret results using the selected data and statistical assumptions.', formula: 'Refer to the metrics and chart annotations on the page.', interpretation: 'Combine numerical results, charts, and engineering knowledge.', limits: 'Results describe the selected sample and do not prove population or causality.', recommendation: 'Verify data quality and assumptions before decisions.' },
  'es-MX': { purpose: 'Explica el propósito y los resultados de esta página.', principle: 'Interpreta con los datos seleccionados y los supuestos estadísticos.', formula: 'Consulta las métricas y anotaciones del gráfico.', interpretation: 'Combina resultados numéricos, gráficos y conocimiento de ingeniería.', limits: 'Los resultados describen la muestra y no prueban población ni causalidad.', recommendation: 'Verifica calidad de datos y supuestos antes de decidir.' },
} as const
const topics: Record<string, Partial<Record<keyof typeof common, Partial<GuideSection>>>> = {
  spc: { 'zh-TW': { purpose: '用控制圖監控製程穩定性與特殊原因變異。', formula: '控制界線通常為中心線 ± 3σ。', recommendation: '先確認時間順序與量測系統，再調查界線外點。' }, en: { purpose: 'Monitor process stability and special-cause variation with control charts.', formula: 'Control limits are commonly center line ± 3σ.', recommendation: 'Verify time order and measurement system before investigating out-of-limit points.' }, 'es-MX': { purpose: 'Monitorea estabilidad y causas especiales con gráficos de control.', formula: 'Los límites suelen ser línea central ± 3σ.', recommendation: 'Verifica orden temporal y sistema de medición antes de investigar puntos fuera de límite.' } },
  modelCenter: { 'zh-TW': { purpose: '比較模型配適、效應與診斷結果。', formula: '依模型類型使用迴歸、ANOVA、SHAP 或敏感度指標。', recommendation: '比較驗證指標與殘差後，再選模型進行實驗。' }, en: { purpose: 'Compare model fit, effects, and diagnostics.', formula: 'Use regression, ANOVA, SHAP, or sensitivity metrics by model type.', recommendation: 'Review validation metrics and residuals before selecting a model for experiments.' }, 'es-MX': { purpose: 'Compara ajuste, efectos y diagnósticos de modelos.', formula: 'Usa regresión, ANOVA, SHAP o sensibilidad según el modelo.', recommendation: 'Revisa métricas de validación y residuos antes de elegir un modelo.' } },
  monteCarlo: { 'zh-TW': { purpose: '依輸入分布抽樣，估計輸出落在規格外的風險。', formula: 'NG 機率 = 超出規格的模擬次數／總模擬次數。', recommendation: '確認抽樣分布、相關性、種子與規格設定，再解讀 NG 機率。' }, en: { purpose: 'Sample input distributions to estimate output specification risk.', formula: 'NG probability = simulations outside specification / total simulations.', recommendation: 'Check distributions, correlations, seed, and specifications before interpreting risk.' }, 'es-MX': { purpose: 'Muestrea distribuciones de entrada para estimar riesgo fuera de especificación.', formula: 'Probabilidad NG = simulaciones fuera de especificación / total.', recommendation: 'Revisa distribuciones, correlaciones, semilla y especificaciones antes de interpretar.' } },
  validation: { 'zh-TW': { purpose: '比較候選模型並規劃可驗證的後續實驗。', recommendation: '確認模型輸入範圍涵蓋實際製程，再執行建議實驗。' }, en: { purpose: 'Compare candidate models and plan verifiable follow-up experiments.', recommendation: 'Ensure model inputs cover the real process before running suggested experiments.' }, 'es-MX': { purpose: 'Compara modelos candidatos y planifica experimentos verificables.', recommendation: 'Asegura que las entradas cubran el proceso real antes de ejecutar experimentos.' } },
  reports: { 'zh-TW': { purpose: '產生可追溯的分析報告與版本紀錄。', recommendation: '檢查報告 metadata、資料集版本與模型版本後再分享。' }, en: { purpose: 'Generate traceable analysis reports and version records.', recommendation: 'Check report metadata, dataset version, and model version before sharing.' }, 'es-MX': { purpose: 'Genera informes de análisis y registros de versión trazables.', recommendation: 'Revisa metadatos, versión de datos y modelo antes de compartir.' } },
}
export function getGuideSection(tab: string, subtab: string | undefined, language: string): GuideSection {
  const lang = (language in common ? language : 'en') as keyof typeof common
  const base = { ...common[lang], title: '' }
  const topic = topics[subtab && tab === 'exploration' ? subtab : tab]?.[lang]
  return { ...base, ...topic, title: '' }
}
